const serviceEndpoints = {
  'authenticationAndAuthorization': 'http://host-machine:10001',
  'kafkaQueue': 'http://host-machine:10002/kafka-queue',
  'core': 'http://host-machine:10003/core',
  'contact': 'http://host-machine:10004/contact',
  'company': 'http://host-machine:10005/company',
  'deal': 'http://host-machine:10006/deal',
  'activity': 'http://host-machine:10007/activity',
  'product': 'http://host-machine:10008/product',
  'importData': 'http://host-machine:10009/import-data',
  'exportData': 'http://host-machine:10010/export-data',
  'textAndCalling': 'http://host-machine:10011/text-and-calling',
  'statistics': 'http://host-machine:10012/statistics',
  'timeline': 'http://host-machine:10013/timeline',
  'email': 'http://host-machine:10014/email',
  'sequence': 'http://host-machine:10015/sequence',
  'notification': 'http://host-machine:10017/notification',
  'apis-v1': 'http://host-machine:8081',
  'apis-v3': 'http://host-machine:8087',
  'bg-tasks': 'http://host-machine:8082',
  'bgTaskAPIDomain': 'http://host-machine:8082',
  'bgTaskAutomationDomain': 'host-machine:8082',
  'messengerSocketCluster': 'http://host-machine:10026',
  'xero': 'http://host-machine:10020/xero',
  'highchartServer': 'http://host-machine:8080',
  'dashboardAndReport': 'http://host-machine:10016/dashboard-and-report',
  'notificationServer': 'http://host-machine:8083',
  'webForms': 'http://host-machine:10024/web-forms',
  'workflow': 'http://host-machine:10019/workflow',
  'subscription': 'http://host-machine:10029/subscription',
};
module.exports = serviceEndpoints;
